[tool.poetry]
name = "ppt"
version = "0.1.0"
description = "ppt – python project template"
authors = ["Mikuláš Zelinka <mikulas@zelinka.dev>"]

[tool.poetry.dependencies]
python = "^3.8"
black = "^20.8b1"
isort = "^5.7.0"
pytest = "^6.2.2"
coverage = "^5.4"
pre-commit = "^2.10.1"
pylint = "^2.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py38']
include = '\.py$'
exclude = ''

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = "119"

[tool.pylint.messages_control]
disable = "C0330, C0326"
