name: Pre-commit checks (black, isort, mypy, flake8, pytest)
on: [push, pull_request]
jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install conda env
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --name base --file conda/python-project-template.yaml --prune
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Using conda and poetry, install the package
      run: |
        poetry install && poetry install pre-commit
    - name: Run all pre-commit tests
      run: |
        poetry run pre-commit
