name: Pre-commit checks (black, isort, mypy, flake8, pytest)
on: [push, pull_request]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
        activate-environment: python-project-template
        environment-file: conda/python-project-template.yaml
    - name: Install poetry
      run: |
        conda env list
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Using conda and poetry, install the package
      run: |
        poetry install
        poetry --version
    - name: Check installed packages (both conda and poetry/pip)
      run: |
        poetry env info
        conda list
        pip list
    - name: Install pre-commit
      run: |
        poetry run pre-commit install
    - name: Run all pre-commit tests
      run: |
        poetry run pre-commit run --all-files
